//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG JSE (https://www.swig.org).
// Version 5.0.6
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class DynArray : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal DynArray(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(DynArray obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(DynArray obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~DynArray() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          octradotnetPINVOKE.delete_DynArray(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public DynArray() : this(octradotnetPINVOKE.new_DynArray__SWIG_0(), true) {
  }

  public DynArray(uint n) : this(octradotnetPINVOKE.new_DynArray__SWIG_1(n), true) {
  }

  public void reserve(uint capacity) {
    octradotnetPINVOKE.DynArray_reserve(swigCPtr, capacity);
  }

  public void push_back(double elmt) {
    octradotnetPINVOKE.DynArray_push_back__SWIG_0(swigCPtr, elmt);
  }

  public void push_back(SWIGTYPE_p_double elmt) {
    octradotnetPINVOKE.DynArray_push_back__SWIG_1(swigCPtr, SWIGTYPE_p_double.swigRelease(elmt));
    if (octradotnetPINVOKE.SWIGPendingException.Pending) throw octradotnetPINVOKE.SWIGPendingException.Retrieve();
  }

  public void clear() {
    octradotnetPINVOKE.DynArray_clear(swigCPtr);
  }

  public uint capacity() {
    uint ret = octradotnetPINVOKE.DynArray_capacity(swigCPtr);
    return ret;
  }

  public uint size() {
    uint ret = octradotnetPINVOKE.DynArray_size(swigCPtr);
    return ret;
  }

  public string to_string() {
    string ret = octradotnetPINVOKE.DynArray_to_string(swigCPtr);
    return ret;
  }

  public void print() {
    octradotnetPINVOKE.DynArray_print(swigCPtr);
  }

  public double get(uint index) {
    double ret = octradotnetPINVOKE.DynArray_get(swigCPtr, index);
    return ret;
  }

  public void set(uint index, double val) {
    octradotnetPINVOKE.DynArray_set(swigCPtr, index, val);
  }

  public SWIGTYPE_p_std__vectorT_double_t to_vec() {
    SWIGTYPE_p_std__vectorT_double_t ret = new SWIGTYPE_p_std__vectorT_double_t(octradotnetPINVOKE.DynArray_to_vec(swigCPtr), true);
    return ret;
  }

}
