//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG JSE (https://www.swig.org).
// Version 5.0.6
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class octradotnet {
  public static int gcd(int x, int y) {
    int ret = octradotnetPINVOKE.gcd(x, y);
    return ret;
  }

  public static void hello_octra() {
    octradotnetPINVOKE.hello_octra();
  }

}
