/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG JSE (https://www.swig.org).
 * Version 5.0.6
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


#define SWIG_VERSION 0x050006
#define SWIGCSHARP

/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

#if defined(__GNUC__)
#  if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#    ifndef GCC_HASCLASSVISIBILITY
#      define GCC_HASCLASSVISIBILITY
#    endif
#  endif
#endif

/* internal SWIG method */
#ifndef SWIGCODESPLIT
# ifndef SWIGINTERN
#   define SWIGINTERN static
# endif
# define SWIGCLINKAGE
# define SWIGCPPLINKAGE
#else
# ifndef SWIGINTERN
#   if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#     define SWIGINTERN
#   else
#     if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#       define SWIGINTERN __attribute__ ((visibility("hidden")))
#     else
#       define SWIGINTERN
#     endif
#   endif
# endif

/* force C linkage */
# ifdef __cplusplus
#   define SWIGCLINKAGE extern "C"
# else
#   define SWIGCLINKAGE
# endif

/* force C++ linkage */
# ifdef __cplusplus
#   define SWIGCPPLINKAGE extern "C++"
# else
#   define SWIGCPPLINKAGE
# endif

#endif // SWIGCODESPLIT

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE static inline
#endif

/* exporting methods */
#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif

/* Deal with Apple's deprecated 'AssertMacros.h' from Carbon-framework */
#if defined(__APPLE__) && !defined(__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES)
# define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0
#endif

/* Intel's compiler complains if a variable which was never initialised is
 * cast to void, which is a common idiom which we use to indicate that we
 * are aware a variable isn't used.  So we just silence that warning.
 * See: https://github.com/swig/swig/issues/192 for more discussion.
 */
#ifdef __INTEL_COMPILER
# pragma warning disable 592
#endif

#if defined(__cplusplus) && __cplusplus >=201103L
# define SWIG_NULLPTR nullptr
# define SWIG_NOEXCEPT noexcept
#else
# define SWIG_NULLPTR NULL
# define SWIG_NOEXCEPT throw()
#endif 

/* -----------------------------------------------------------------------------
 * swigcompat.swg
 *
 * Macros to provide support compatibility with older C and C++ standards.
 *
 * Note that SWIG expects __cplusplus to be defined to the appropriate C++ standard.
 * MSVC users are urged to check and examine the /Zc:__cplusplus compiler option.
 * See https://learn.microsoft.com/en-us/cpp/build/reference/zc-cplusplus.
 * ----------------------------------------------------------------------------- */

/* C99 and C++11 should provide snprintf, but define SWIG_NO_SNPRINTF
 * if you're missing it.
 */
#if ((defined __STDC_VERSION__ && __STDC_VERSION__ >= 199901L) || \
     (defined __cplusplus && __cplusplus >= 201103L) || \
     defined SWIG_HAVE_SNPRINTF) && \
    !defined SWIG_NO_SNPRINTF
# define SWIG_snprintf(O,S,F,A) snprintf(O,S,F,A)
# define SWIG_snprintf2(O,S,F,A,B) snprintf(O,S,F,A,B)
#else
/* Fallback versions ignore the buffer size, but most of our uses either have a
 * fixed maximum possible size or dynamically allocate a buffer that's large
 * enough.
 */
# define SWIG_snprintf(O,S,F,A) sprintf(O,F,A)
# define SWIG_snprintf2(O,S,F,A,B) sprintf(O,F,A,B)
#endif


#include <stdlib.h>
#include <string.h>
#include <stdio.h>


/* Support for throwing C# exceptions from C/C++. There are two types: 
 * Exceptions that take a message and ArgumentExceptions that take a message and a parameter name. */
typedef enum {
  SWIG_CSharpApplicationException,
  SWIG_CSharpArithmeticException,
  SWIG_CSharpDivideByZeroException,
  SWIG_CSharpIndexOutOfRangeException,
  SWIG_CSharpInvalidCastException,
  SWIG_CSharpInvalidOperationException,
  SWIG_CSharpIOException,
  SWIG_CSharpNullReferenceException,
  SWIG_CSharpOutOfMemoryException,
  SWIG_CSharpOverflowException,
  SWIG_CSharpSystemException
} SWIG_CSharpExceptionCodes;

typedef enum {
  SWIG_CSharpArgumentException,
  SWIG_CSharpArgumentNullException,
  SWIG_CSharpArgumentOutOfRangeException
} SWIG_CSharpExceptionArgumentCodes;

typedef void (SWIGSTDCALL* SWIG_CSharpExceptionCallback_t)(const char *);
typedef void (SWIGSTDCALL* SWIG_CSharpExceptionArgumentCallback_t)(const char *, const char *);

typedef struct {
  SWIG_CSharpExceptionCodes code;
  SWIG_CSharpExceptionCallback_t callback;
} SWIG_CSharpException_t;

typedef struct {
  SWIG_CSharpExceptionArgumentCodes code;
  SWIG_CSharpExceptionArgumentCallback_t callback;
} SWIG_CSharpExceptionArgument_t;

static SWIG_CSharpException_t SWIG_csharp_exceptions[] = {
  { SWIG_CSharpApplicationException, NULL },
  { SWIG_CSharpArithmeticException, NULL },
  { SWIG_CSharpDivideByZeroException, NULL },
  { SWIG_CSharpIndexOutOfRangeException, NULL },
  { SWIG_CSharpInvalidCastException, NULL },
  { SWIG_CSharpInvalidOperationException, NULL },
  { SWIG_CSharpIOException, NULL },
  { SWIG_CSharpNullReferenceException, NULL },
  { SWIG_CSharpOutOfMemoryException, NULL },
  { SWIG_CSharpOverflowException, NULL },
  { SWIG_CSharpSystemException, NULL }
};

static SWIG_CSharpExceptionArgument_t SWIG_csharp_exceptions_argument[] = {
  { SWIG_CSharpArgumentException, NULL },
  { SWIG_CSharpArgumentNullException, NULL },
  { SWIG_CSharpArgumentOutOfRangeException, NULL }
};

static void SWIGUNUSED SWIG_CSharpSetPendingException(SWIG_CSharpExceptionCodes code, const char *msg) {
  SWIG_CSharpExceptionCallback_t callback = SWIG_csharp_exceptions[SWIG_CSharpApplicationException].callback;
  if ((size_t)code < sizeof(SWIG_csharp_exceptions)/sizeof(SWIG_CSharpException_t)) {
    callback = SWIG_csharp_exceptions[code].callback;
  }
  callback(msg);
}

static void SWIGUNUSED SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpExceptionArgumentCodes code, const char *msg, const char *param_name) {
  SWIG_CSharpExceptionArgumentCallback_t callback = SWIG_csharp_exceptions_argument[SWIG_CSharpArgumentException].callback;
  if ((size_t)code < sizeof(SWIG_csharp_exceptions_argument)/sizeof(SWIG_CSharpExceptionArgument_t)) {
    callback = SWIG_csharp_exceptions_argument[code].callback;
  }
  callback(msg, param_name);
}


#ifdef __cplusplus
extern "C" 
#endif
SWIGEXPORT void SWIGSTDCALL SWIGRegisterExceptionCallbacks_octradotnet(
                                                SWIG_CSharpExceptionCallback_t applicationCallback,
                                                SWIG_CSharpExceptionCallback_t arithmeticCallback,
                                                SWIG_CSharpExceptionCallback_t divideByZeroCallback, 
                                                SWIG_CSharpExceptionCallback_t indexOutOfRangeCallback, 
                                                SWIG_CSharpExceptionCallback_t invalidCastCallback,
                                                SWIG_CSharpExceptionCallback_t invalidOperationCallback,
                                                SWIG_CSharpExceptionCallback_t ioCallback,
                                                SWIG_CSharpExceptionCallback_t nullReferenceCallback,
                                                SWIG_CSharpExceptionCallback_t outOfMemoryCallback, 
                                                SWIG_CSharpExceptionCallback_t overflowCallback, 
                                                SWIG_CSharpExceptionCallback_t systemCallback) {
  SWIG_csharp_exceptions[SWIG_CSharpApplicationException].callback = applicationCallback;
  SWIG_csharp_exceptions[SWIG_CSharpArithmeticException].callback = arithmeticCallback;
  SWIG_csharp_exceptions[SWIG_CSharpDivideByZeroException].callback = divideByZeroCallback;
  SWIG_csharp_exceptions[SWIG_CSharpIndexOutOfRangeException].callback = indexOutOfRangeCallback;
  SWIG_csharp_exceptions[SWIG_CSharpInvalidCastException].callback = invalidCastCallback;
  SWIG_csharp_exceptions[SWIG_CSharpInvalidOperationException].callback = invalidOperationCallback;
  SWIG_csharp_exceptions[SWIG_CSharpIOException].callback = ioCallback;
  SWIG_csharp_exceptions[SWIG_CSharpNullReferenceException].callback = nullReferenceCallback;
  SWIG_csharp_exceptions[SWIG_CSharpOutOfMemoryException].callback = outOfMemoryCallback;
  SWIG_csharp_exceptions[SWIG_CSharpOverflowException].callback = overflowCallback;
  SWIG_csharp_exceptions[SWIG_CSharpSystemException].callback = systemCallback;
}

#ifdef __cplusplus
extern "C" 
#endif
SWIGEXPORT void SWIGSTDCALL SWIGRegisterExceptionArgumentCallbacks_octradotnet(
                                                SWIG_CSharpExceptionArgumentCallback_t argumentCallback,
                                                SWIG_CSharpExceptionArgumentCallback_t argumentNullCallback,
                                                SWIG_CSharpExceptionArgumentCallback_t argumentOutOfRangeCallback) {
  SWIG_csharp_exceptions_argument[SWIG_CSharpArgumentException].callback = argumentCallback;
  SWIG_csharp_exceptions_argument[SWIG_CSharpArgumentNullException].callback = argumentNullCallback;
  SWIG_csharp_exceptions_argument[SWIG_CSharpArgumentOutOfRangeException].callback = argumentOutOfRangeCallback;
}


/* Callback for returning strings to C# without leaking memory */
typedef char * (SWIGSTDCALL* SWIG_CSharpStringHelperCallback)(const char *);
static SWIG_CSharpStringHelperCallback SWIG_csharp_string_callback = NULL;


#ifdef __cplusplus
extern "C" 
#endif
SWIGEXPORT void SWIGSTDCALL SWIGRegisterStringCallback_octradotnet(SWIG_CSharpStringHelperCallback callback) {
  SWIG_csharp_string_callback = callback;
}


/* Contract support */

#define SWIG_contract_assert(nullreturn, expr, msg) do { if (!(expr)) {SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, msg, ""); return nullreturn; } } while (0)


#ifdef __cplusplus
#include <utility>
/* SwigValueWrapper is described in swig.swg */
template<typename T> class SwigValueWrapper {
  struct SwigSmartPointer {
    T *ptr;
    SwigSmartPointer(T *p) : ptr(p) { }
    ~SwigSmartPointer() { delete ptr; }
    SwigSmartPointer& operator=(SwigSmartPointer& rhs) { T* oldptr = ptr; ptr = 0; delete oldptr; ptr = rhs.ptr; rhs.ptr = 0; return *this; }
    void reset(T *p) { T* oldptr = ptr; ptr = 0; delete oldptr; ptr = p; }
  } pointer;
  SwigValueWrapper& operator=(const SwigValueWrapper<T>& rhs);
  SwigValueWrapper(const SwigValueWrapper<T>& rhs);
public:
  SwigValueWrapper() : pointer(0) { }
  SwigValueWrapper& operator=(const T& t) { SwigSmartPointer tmp(new T(t)); pointer = tmp; return *this; }
#if __cplusplus >=201103L
  SwigValueWrapper& operator=(T&& t) { SwigSmartPointer tmp(new T(std::move(t))); pointer = tmp; return *this; }
  operator T&&() const { return std::move(*pointer.ptr); }
#else
  operator T&() const { return *pointer.ptr; }
#endif
  T *operator&() const { return pointer.ptr; }
  static void reset(SwigValueWrapper& t, T *p) { t.pointer.reset(p); }
};

/*
 * SwigValueInit() is a generic initialisation solution as the following approach:
 * 
 *       T c_result = T();
 * 
 * doesn't compile for all types for example:
 * 
 *       unsigned int c_result = unsigned int();
 */
template <typename T> T SwigValueInit() {
  return T();
}

#if __cplusplus >=201103L
# define SWIG_STD_MOVE(OBJ) std::move(OBJ)
#else
# define SWIG_STD_MOVE(OBJ) OBJ
#endif

#endif


#include <string>


  #include "octra/cxx/dynarray.hpp"


#include <memory>


  #include "octra/cxx/circle.hpp"


  #include "octra/cxx/hello.hpp"


#ifdef __cplusplus
extern "C" {
#endif

SWIGEXPORT void * SWIGSTDCALL CSharp_new_DynArray__SWIG_0() {
  void * jresult ;
  octra::DynArray< double > *result = 0 ;
  
  result = (octra::DynArray< double > *)new octra::DynArray< double >();
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_DynArray__SWIG_1(unsigned int jarg1) {
  void * jresult ;
  size_t arg1 ;
  octra::DynArray< double > *result = 0 ;
  
  arg1 = (size_t)jarg1; 
  result = (octra::DynArray< double > *)new octra::DynArray< double >(SWIG_STD_MOVE(arg1));
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_delete_DynArray(void * jarg1) {
  octra::DynArray< double > *arg1 = 0 ;
  
  arg1 = (octra::DynArray< double > *)jarg1; 
  delete arg1;
}


SWIGEXPORT void SWIGSTDCALL CSharp_DynArray_reserve(void * jarg1, unsigned int jarg2) {
  octra::DynArray< double > *arg1 = 0 ;
  size_t arg2 ;
  
  arg1 = (octra::DynArray< double > *)jarg1; 
  arg2 = (size_t)jarg2; 
  (arg1)->reserve(SWIG_STD_MOVE(arg2));
}


SWIGEXPORT void SWIGSTDCALL CSharp_DynArray_push_back__SWIG_0(void * jarg1, double jarg2) {
  octra::DynArray< double > *arg1 = 0 ;
  double *arg2 = 0 ;
  double temp2 ;
  
  arg1 = (octra::DynArray< double > *)jarg1; 
  temp2 = (double)jarg2; 
  arg2 = &temp2; 
  (arg1)->push_back((double const &)*arg2);
}


SWIGEXPORT void SWIGSTDCALL CSharp_DynArray_push_back__SWIG_1(void * jarg1, void * jarg2) {
  octra::DynArray< double > *arg1 = 0 ;
  double *arg2 = 0 ;
  std::unique_ptr< double > rvrdeleter2 ;
  
  arg1 = (octra::DynArray< double > *)jarg1; 
  arg2 = (double *)jarg2;
  if (!arg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "double && is null", 0);
    return ;
  }
  rvrdeleter2.reset(arg2); 
  (arg1)->push_back((double &&)*arg2);
}


SWIGEXPORT void SWIGSTDCALL CSharp_DynArray_clear(void * jarg1) {
  octra::DynArray< double > *arg1 = 0 ;
  
  arg1 = (octra::DynArray< double > *)jarg1; 
  (arg1)->clear();
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_DynArray_capacity(void * jarg1) {
  unsigned int jresult ;
  octra::DynArray< double > *arg1 = 0 ;
  size_t result;
  
  arg1 = (octra::DynArray< double > *)jarg1; 
  result = ((octra::DynArray< double > const *)arg1)->capacity();
  jresult = (unsigned int)result; 
  return jresult;
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_DynArray_size(void * jarg1) {
  unsigned int jresult ;
  octra::DynArray< double > *arg1 = 0 ;
  size_t result;
  
  arg1 = (octra::DynArray< double > *)jarg1; 
  result = ((octra::DynArray< double > const *)arg1)->size();
  jresult = (unsigned int)result; 
  return jresult;
}


SWIGEXPORT const char * SWIGSTDCALL CSharp_DynArray_to_string(void * jarg1) {
  const char * jresult ;
  octra::DynArray< double > *arg1 = 0 ;
  std::string result;
  
  arg1 = (octra::DynArray< double > *)jarg1; 
  result = ((octra::DynArray< double > const *)arg1)->to_string();
  jresult = SWIG_csharp_string_callback((&result)->c_str()); 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_DynArray_print(void * jarg1) {
  octra::DynArray< double > *arg1 = 0 ;
  
  arg1 = (octra::DynArray< double > *)jarg1; 
  (arg1)->print();
}


SWIGEXPORT double SWIGSTDCALL CSharp_DynArray_get(void * jarg1, unsigned int jarg2) {
  double jresult ;
  octra::DynArray< double > *arg1 = 0 ;
  size_t arg2 ;
  double result;
  
  arg1 = (octra::DynArray< double > *)jarg1; 
  arg2 = (size_t)jarg2; 
  result = (double)((octra::DynArray< double > const *)arg1)->get(SWIG_STD_MOVE(arg2));
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_DynArray_set(void * jarg1, unsigned int jarg2, double jarg3) {
  octra::DynArray< double > *arg1 = 0 ;
  size_t arg2 ;
  double arg3 ;
  
  arg1 = (octra::DynArray< double > *)jarg1; 
  arg2 = (size_t)jarg2; 
  arg3 = (double)jarg3; 
  (arg1)->set(SWIG_STD_MOVE(arg2),arg3);
}


SWIGEXPORT void * SWIGSTDCALL CSharp_DynArray_to_vec(void * jarg1) {
  void * jresult ;
  octra::DynArray< double > *arg1 = 0 ;
  std::vector< double > result;
  
  arg1 = (octra::DynArray< double > *)jarg1; 
  result = ((octra::DynArray< double > const *)arg1)->to_vec();
  jresult = new std::vector< double >(result); 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_DynArrayInt__SWIG_0() {
  void * jresult ;
  octra::DynArray< int > *result = 0 ;
  
  result = (octra::DynArray< int > *)new octra::DynArray< int >();
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_DynArrayInt__SWIG_1(unsigned int jarg1) {
  void * jresult ;
  size_t arg1 ;
  octra::DynArray< int > *result = 0 ;
  
  arg1 = (size_t)jarg1; 
  result = (octra::DynArray< int > *)new octra::DynArray< int >(SWIG_STD_MOVE(arg1));
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_delete_DynArrayInt(void * jarg1) {
  octra::DynArray< int > *arg1 = 0 ;
  
  arg1 = (octra::DynArray< int > *)jarg1; 
  delete arg1;
}


SWIGEXPORT void SWIGSTDCALL CSharp_DynArrayInt_reserve(void * jarg1, unsigned int jarg2) {
  octra::DynArray< int > *arg1 = 0 ;
  size_t arg2 ;
  
  arg1 = (octra::DynArray< int > *)jarg1; 
  arg2 = (size_t)jarg2; 
  (arg1)->reserve(SWIG_STD_MOVE(arg2));
}


SWIGEXPORT void SWIGSTDCALL CSharp_DynArrayInt_push_back__SWIG_0(void * jarg1, int jarg2) {
  octra::DynArray< int > *arg1 = 0 ;
  int *arg2 = 0 ;
  int temp2 ;
  
  arg1 = (octra::DynArray< int > *)jarg1; 
  temp2 = (int)jarg2; 
  arg2 = &temp2; 
  (arg1)->push_back((int const &)*arg2);
}


SWIGEXPORT void SWIGSTDCALL CSharp_DynArrayInt_push_back__SWIG_1(void * jarg1, void * jarg2) {
  octra::DynArray< int > *arg1 = 0 ;
  int *arg2 = 0 ;
  std::unique_ptr< int > rvrdeleter2 ;
  
  arg1 = (octra::DynArray< int > *)jarg1; 
  arg2 = (int *)jarg2;
  if (!arg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "int && is null", 0);
    return ;
  }
  rvrdeleter2.reset(arg2); 
  (arg1)->push_back((int &&)*arg2);
}


SWIGEXPORT void SWIGSTDCALL CSharp_DynArrayInt_clear(void * jarg1) {
  octra::DynArray< int > *arg1 = 0 ;
  
  arg1 = (octra::DynArray< int > *)jarg1; 
  (arg1)->clear();
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_DynArrayInt_capacity(void * jarg1) {
  unsigned int jresult ;
  octra::DynArray< int > *arg1 = 0 ;
  size_t result;
  
  arg1 = (octra::DynArray< int > *)jarg1; 
  result = ((octra::DynArray< int > const *)arg1)->capacity();
  jresult = (unsigned int)result; 
  return jresult;
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_DynArrayInt_size(void * jarg1) {
  unsigned int jresult ;
  octra::DynArray< int > *arg1 = 0 ;
  size_t result;
  
  arg1 = (octra::DynArray< int > *)jarg1; 
  result = ((octra::DynArray< int > const *)arg1)->size();
  jresult = (unsigned int)result; 
  return jresult;
}


SWIGEXPORT const char * SWIGSTDCALL CSharp_DynArrayInt_to_string(void * jarg1) {
  const char * jresult ;
  octra::DynArray< int > *arg1 = 0 ;
  std::string result;
  
  arg1 = (octra::DynArray< int > *)jarg1; 
  result = ((octra::DynArray< int > const *)arg1)->to_string();
  jresult = SWIG_csharp_string_callback((&result)->c_str()); 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_DynArrayInt_print(void * jarg1) {
  octra::DynArray< int > *arg1 = 0 ;
  
  arg1 = (octra::DynArray< int > *)jarg1; 
  (arg1)->print();
}


SWIGEXPORT int SWIGSTDCALL CSharp_DynArrayInt_get(void * jarg1, unsigned int jarg2) {
  int jresult ;
  octra::DynArray< int > *arg1 = 0 ;
  size_t arg2 ;
  int result;
  
  arg1 = (octra::DynArray< int > *)jarg1; 
  arg2 = (size_t)jarg2; 
  result = (int)((octra::DynArray< int > const *)arg1)->get(SWIG_STD_MOVE(arg2));
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_DynArrayInt_set(void * jarg1, unsigned int jarg2, int jarg3) {
  octra::DynArray< int > *arg1 = 0 ;
  size_t arg2 ;
  int arg3 ;
  
  arg1 = (octra::DynArray< int > *)jarg1; 
  arg2 = (size_t)jarg2; 
  arg3 = (int)jarg3; 
  (arg1)->set(SWIG_STD_MOVE(arg2),arg3);
}


SWIGEXPORT void * SWIGSTDCALL CSharp_DynArrayInt_to_vec(void * jarg1) {
  void * jresult ;
  octra::DynArray< int > *arg1 = 0 ;
  std::vector< int > result;
  
  arg1 = (octra::DynArray< int > *)jarg1; 
  result = ((octra::DynArray< int > const *)arg1)->to_vec();
  jresult = new std::vector< int >(result); 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_gcd(int jarg1, int jarg2) {
  int jresult ;
  int arg1 ;
  int arg2 ;
  int result;
  
  arg1 = (int)jarg1; 
  arg2 = (int)jarg2; 
  result = (int)octra::gcd(arg1,arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_Circle_m_radius_set(void * jarg1, double jarg2) {
  octra::Circle *arg1 = 0 ;
  double arg2 ;
  
  arg1 = (octra::Circle *)jarg1; 
  arg2 = (double)jarg2; 
  if (arg1) (arg1)->m_radius = arg2;
}


SWIGEXPORT double SWIGSTDCALL CSharp_Circle_m_radius_get(void * jarg1) {
  double jresult ;
  octra::Circle *arg1 = 0 ;
  double result;
  
  arg1 = (octra::Circle *)jarg1; 
  result = (double) ((arg1)->m_radius);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_Circle(double jarg1) {
  void * jresult ;
  double arg1 ;
  octra::Circle *result = 0 ;
  
  arg1 = (double)jarg1; 
  result = (octra::Circle *)new octra::Circle(arg1);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT double SWIGSTDCALL CSharp_Circle_area(void * jarg1) {
  double jresult ;
  octra::Circle *arg1 = 0 ;
  double result;
  
  arg1 = (octra::Circle *)jarg1; 
  result = (double)(arg1)->area();
  jresult = result; 
  return jresult;
}


SWIGEXPORT double SWIGSTDCALL CSharp_Circle_perimeter(void * jarg1) {
  double jresult ;
  octra::Circle *arg1 = 0 ;
  double result;
  
  arg1 = (octra::Circle *)jarg1; 
  result = (double)(arg1)->perimeter();
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_delete_Circle(void * jarg1) {
  octra::Circle *arg1 = 0 ;
  
  arg1 = (octra::Circle *)jarg1; 
  delete arg1;
}


SWIGEXPORT void SWIGSTDCALL CSharp_hello_octra() {
  octra::hello_octra();
}


#ifdef __cplusplus
}
#endif

